# Generated by Django 5.2.10 on 2026-03-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0016_add_ingesterror"),
        ("ingest", "0017_eventdeduplicationlog"),
    ]

    operations = []
