# Generated by Django 5.2.10 on 2026-03-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0023_merge_all_conflicting_migrations"),
        ("ingest", "0024_merge_20260328_1903"),
    ]

    operations = []
