# Generated by Django 5.2.10 on 2026-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0027_merge_20260330_0853"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="trackedcontract",
            name="ingest_trac_evt_filter_type_idx",
        ),
        migrations.RenameIndex(
            model_name="ingesterror",
            new_name="ingest_inge_error_t_0174ca_idx",
            old_name="ingest_inge_error_t_b8e123_idx",
        ),
        migrations.RenameIndex(
            model_name="ingesterror",
            new_name="ingest_inge_created_fcf0ee_idx",
            old_name="ingest_inge_created_f8a456_idx",
        ),
        migrations.RenameIndex(
            model_name="trackedcontract",
            new_name="ingest_trac_alias_00de2f_idx",
            old_name="ingest_trac_alias_idx",
        ),
        migrations.AddField(
            model_name="trackedcontract",
            name="json_schema",
            field=models.JSONField(
                blank=True,
                help_text="Optional JSON schema for validating decoded event payloads",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="duration_ms",
            field=models.FloatField(
                blank=True,
                help_text="Time taken for the webhook HTTP request in milliseconds",
                null=True,
            ),
        ),
    ]
