# Generated by Django 5.2.5 on 2026-03-30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0030_webhook_backoff_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedcontract",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of free-form tags for organizing contracts (e.g. payment, governance, test).",
            ),
        ),
        migrations.AddField(
            model_name="webhooksubscription",
            name="max_retries",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Maximum number of retry attempts before the webhook is suspended (1-20).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.CreateModel(
            name="ContractIngestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC time when this ingest run summary was recorded",
                    ),
                ),
                (
                    "ledger_from",
                    models.PositiveBigIntegerField(
                        help_text="First ledger covered by this ingest run",
                    ),
                ),
                (
                    "ledger_to",
                    models.PositiveBigIntegerField(
                        help_text="Last ledger covered by this ingest run",
                    ),
                ),
                (
                    "event_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of events processed for this ledger range",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_history",
                        to="ingest.trackedcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["contract", "-timestamp"], name="ingest_cont_contrac_5f0e67_idx"),
                    models.Index(fields=["contract", "ledger_from", "ledger_to"], name="ingest_cont_contrac_85f373_idx"),
                ],
            },
        ),
    ]
