# Generated by Django 5.2.10 on 2026-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0038_dependencyimpactassessment_organizationbudget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='success_count',
            field=models.PositiveIntegerField(default=0, help_text='Total successful delivery attempts'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='total_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Total failed delivery attempts'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive failures since last success'),
        ),
    ]
