# Generated by Django 5.2.10 on 2026-05-31 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0041_eventdeduplicationconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooksubscription',
            name='retry_backoff_seconds',
            field=models.PositiveIntegerField(default=2, help_text='Base seconds for backoff calculation (e.g. 2s, 4s, 8s...) (1-3600, default: 2)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.CreateModel(
            name='ContractCompletenessSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField(db_index=True, help_text='Start of the SLA hour bucket (UTC)')),
                ('events_expected', models.PositiveIntegerField(default=0, help_text='Expected events based on RPC data')),
                ('events_indexed', models.PositiveIntegerField(default=0, help_text='Actually indexed events')),
                ('sla_percentage', models.FloatField(default=100.0, help_text='Percentage of events indexed')),
                ('is_violated', models.BooleanField(db_index=True, default=False, help_text='True if SLA < threshold')),
                ('alert_sent', models.BooleanField(default=False, help_text='Whether an alert was sent for this violation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_records', to='ingest.trackedcontract')),
            ],
            options={
                'ordering': ['-hour_start'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('period_start', models.DateField(help_text='Start of billing period')),
                ('period_end', models.DateField(help_text='End of billing period')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('line_items', models.JSONField(blank=True, default=list, help_text='Invoice line items')),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='ingest.organization')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sla_violation', 'SLA Violation'), ('sla_recovery', 'SLA Recovery')], max_length=32)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_alerts', to='ingest.trackedcontract')),
                ('sla_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ingest.contractcompletenesssla')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contractcompletenesssla',
            index=models.Index(fields=['contract', 'hour_start'], name='ingest_cont_contrac_b79a48_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcompletenesssla',
            index=models.Index(fields=['is_violated', 'hour_start'], name='ingest_cont_is_viol_b3965c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractcompletenesssla',
            unique_together={('contract', 'hour_start')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'issued_at'], name='ingest_invo_organiz_19cb60_idx'),
        ),
        migrations.AddIndex(
            model_name='slaalert',
            index=models.Index(fields=['contract', 'triggered_at'], name='ingest_slaa_contrac_190062_idx'),
        ),
        migrations.AddIndex(
            model_name='slaalert',
            index=models.Index(fields=['alert_type', 'triggered_at'], name='ingest_slaa_alert_t_7e8d0f_idx'),
        ),
    ]
