# Generated by merge conflict resolution.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0042_add_invoice_model"),
        ("ingest", "0042_blacklistedcontract"),
    ]

    operations = []
