# Generated by Django 5.2.10 on 2026-06-02 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0042_blacklistedcontract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooksubscription",
            name="retry_backoff_seconds",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Base seconds for backoff calculation (e.g. 2s, 4s, 8s...) (1-3600, default: 2)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3600),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="webhooksubscription",
            constraint=models.UniqueConstraint(
                fields=("target_url", "contract"),
                name="unique_url_contract_subscription",
            ),
        ),
    ]
