# Generated by Django 5.2.10 on 2026-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0044_contractevent_payload_compression'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cors_origins',
            field=models.JSONField(blank=True, default=list, help_text='CORS allowed origins for this organization (list of strings)'),
        ),
    ]
