# Generated by Django 5.2.10 on 2026-06-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0045_organization_cors_origins"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("last_event_time", models.DateTimeField(null=True)),
                ("minutes_since_last_event", models.IntegerField()),
                ("error_message", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingest.trackedcontract",
                    ),
                ),
            ],
        ),
    ]
