# Generated by Django 5.2.10 on 2026-06-30 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0045_organization_cors_origins"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ledger_sequence", models.PositiveBigIntegerField(db_index=True)),
                (
                    "state_data",
                    models.JSONField(help_text="Contract state JSON at capture time"),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="ingest.trackedcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-ledger_sequence"],
            },
        ),
        migrations.CreateModel(
            name="StateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(db_index=True, max_length=512)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("insert", "Insert"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        default="update",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_changes",
                        to="ingest.contractsnapshot",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="ingest.contractsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["field_name", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contractsnapshot",
            index=models.Index(
                fields=["contract", "-ledger_sequence"],
                name="ingest_cont_contrac_82040f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractsnapshot",
            unique_together={("contract", "ledger_sequence")},
        ),
        migrations.AddIndex(
            model_name="statechange",
            index=models.Index(
                fields=["snapshot", "field_name"], name="ingest_stat_snapsho_e61669_idx"
            ),
        ),
    ]
