# Generated by Django 5.2.10 on 2026-07-24 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0046_contract_snapshot_state_change"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedcontract",
            name="is_paused",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When true, ingestion is suspended; historical data stays queryable.",
            ),
        ),
        migrations.AddField(
            model_name="trackedcontract",
            name="pause_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Audit trail: why this contract was paused.",
            ),
        ),
        migrations.AddField(
            model_name="trackedcontract",
            name="paused_at",
            field=models.DateTimeField(
                blank=True, help_text="When this contract was paused.", null=True
            ),
        ),
        migrations.AddField(
            model_name="trackedcontract",
            name="resume_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, the contract auto-resumes at this time.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="trackedcontract",
            index=models.Index(
                fields=["is_paused", "resume_at"], name="ingest_trac_is_paus_774739_idx"
            ),
        ),
    ]
