# Generated by Django 5.2.10 on 2026-08-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0050_transactioncost"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventaggregation",
            name="unique_contract_event_type_timestamp",
        ),
        migrations.RemoveConstraint(
            model_name="transactioncostaggregation",
            name="unique_cost_agg_contract_fn_ts",
        ),
        migrations.RenameIndex(
            model_name="eventaggregation",
            new_name="ingest_even_contrac_c734ef_idx",
            old_name="ingest_evag_contract_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="eventaggregation",
            new_name="ingest_even_timesta_03d6d0_idx",
            old_name="ingest_evag_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="eventaggregation",
            new_name="ingest_even_contrac_39b2d5_idx",
            old_name="ingest_evag_ctr_evtype_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdeliverylog",
            new_name="ingest_webh_subscri_42647a_idx",
            old_name="ingest_whde_sub_status_idx",
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="cpu_instructions_used",
            field=models.BigIntegerField(
                default=0, help_text="CPU instructions consumed (Soroban compute units)"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="function_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Contract function name (empty if not determinable from RPC)",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="inclusion_fee_stroops",
            field=models.BigIntegerField(
                default=0, help_text="Base inclusion / network fee portion in stroops"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="is_outlier",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when total_fee_stroops exceeds mean + 2 × std-dev for the same (contract, function_name) group",
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="memory_bytes_used",
            field=models.BigIntegerField(
                default=0, help_text="Memory bytes used by the Soroban host"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="read_bytes_used",
            field=models.BigIntegerField(
                default=0, help_text="Ledger-entry read bytes"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="resource_fee_stroops",
            field=models.BigIntegerField(
                default=0, help_text="Soroban resource fee portion in stroops"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="total_fee_stroops",
            field=models.BigIntegerField(
                default=0, help_text="Total fee charged for the transaction in stroops"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncost",
            name="write_bytes_used",
            field=models.BigIntegerField(
                default=0, help_text="Ledger-entry write bytes"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncostaggregation",
            name="function_name",
            field=models.CharField(
                db_index=True,
                help_text="Function name, or '' for the contract-level total bucket.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transactioncostaggregation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncostaggregation",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, help_text="Start of the 1-hour bucket (UTC)."
            ),
        ),
        migrations.AlterField(
            model_name="webhookdeliverylog",
            name="response_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="First 4 KB of the subscriber response body (truncated if longer)",
            ),
        ),
        migrations.AlterField(
            model_name="webhookdeliverylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("dead_letter", "Dead Letter"),
                ],
                db_index=True,
                default="pending",
                help_text="Delivery status: pending → success | failed → dead_letter",
                max_length=16,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventaggregation",
            unique_together={("contract", "event_type", "timestamp")},
        ),
        migrations.AlterUniqueTogether(
            name="transactioncostaggregation",
            unique_together={("contract", "function_name", "timestamp")},
        ),
    ]
