# Generated by Django 5.2.10 on 2026-08-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingest",
            "0051_remove_eventaggregation_unique_contract_event_type_timestamp_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookReplayJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.CharField(db_index=True, max_length=56)),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Replay filters: event_type, from_date, to_date, ledgers, limit, dry_run",
                    ),
                ),
                (
                    "rate_limit_per_second",
                    models.FloatField(
                        default=5.0,
                        help_text="Max webhook dispatches per second during replay",
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total_events", models.PositiveIntegerField(default=0)),
                ("processed_events", models.PositiveIntegerField(default=0)),
                ("succeeded", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_replay_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional specific subscription; when null, all active webhooks for the contract",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replay_jobs",
                        to="ingest.webhooksubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="ingest_webh_status_eb9dbf_idx",
                    ),
                    models.Index(
                        fields=["contract_id", "created_at"],
                        name="ingest_webh_contrac_3d116c_idx",
                    ),
                ],
            },
        ),
    ]
