# Generated by Django 5.2.10 on 2026-08-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0054_contractevent_partitioning"),
        ("ingest", "0054_contractevent_payload_zstd"),
        ("ingest", "0054_organization_tier"),
    ]

    operations = []
