# Generated by Django 5.2.10 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):
    """Issue #1407 - composite index for ContractEvent ledger-window lookups.

    Ledger range queries filtered by ``contract_id`` and ordered by recency
    could not be served by the existing ``(contract, ledger, event_index)``
    unique index because the trailing ``timestamp`` ordering is not part of
    it, so PostgreSQL fell back to scanning the matched range.
    """

    dependencies = [
        ("ingest", "0055_merge_20260831_1259"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contractevent",
            index=models.Index(
                fields=["contract", "ledger", "timestamp"],
                name="idx_event_contract_ledger_ts",
            ),
        ),
    ]
